### ISSUE TITLE
abbreviation preview doesn't work

### ISSUE THREAD

**Issue by Nisseboy** [emmetio/codemirror-plugin#25]
I have a project using codemirror and emmetio which uses some other functionality from codemirror.
The preview of abbreviation does not show up.
I have tried removing all extra functinality except for syntax highlighting and sublime however that did not work (emmet didn't even work at all without syntax highlighting)

there are no errors and i can use emmet as usual just without the preview.

help?

**Comment by sergeche** [comment]
The preview is displayed for a known syntaxes only like HTML, CSS etc. I don’t know how exactly you use Emmet in your project, have to see your config

**Comment by Nisseboy** [comment]
![image](https://user-images.githubusercontent.com/60318517/183476983-cce0b1fe-b5f7-4c33-b503-f8070a99deab.png)
That is indeed correct lib\emmetio.js
![image](https://user-images.githubusercontent.com/60318517/183477128-a8ed947f-5ead-4f54-b925-2084d6b57e23.png)

**Comment by sergeche** [comment]
Not sure what `lib/emmetio.js` stands for. There’s `dist/browser.js` file in `@emmetio/codemirror-plugin` npm package

**Comment by Nisseboy** [comment]
Ah right i forgot about that, i just took the browserjs file and renamed it to emmetio.js, i will however try using the whole repository and seeing if that helps

**Comment by Nisseboy** [comment]
Nope, i installed using npm, got the whole repo, did not rename anything but still the same problem.
Autocomplete with emmet works but no preview.

![image](https://user-images.githubusercontent.com/60318517/183703068-10652131-ad5a-4a12-aafe-03e91d64133b.png)
![image](https://user-images.githubusercontent.com/60318517/183703236-535f5985-f8fc-4b05-a7cd-c87dbda1ce6b.png)

**Comment by sergeche** [comment]
Just checked with bundled [example](https://github.com/emmetio/codemirror-plugin/blob/master/example/index.html) and everything works fine. Since you didn’t provided your CM config, I guess you should match it with example

**Comment by Nisseboy** [comment]
Thank you, i will try that when i get home

**Comment by Nisseboy** [comment]
I am sorry for wasting your time, i tried the example and it worked perfectly, so i tried the same code in my project which did not work.
I then transplanted a few source files into my project and it worked.

The reason for that is that on line 153 in codemirror.css i had changed position relative to absolute to solve another issue, this caused emmetio previews to break.
